# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Prepare environment
      run: |
        sudo xcode-select --path /Applications/Xcode_10.3.app
        mkdir -p provisioning_profiles
        echo '${{ secrets.main_provisioning_profile }}' | base64 --decode > provisioning_profiles/main.mobileprovision
        echo '${{ secrets.share_extension_provisioning_profile }}' | base64 --decode > provisioning_profiles/share_extension.mobileprovision
        echo '${{ secrets.siri_intents_provisioning_profile }}' | base64 --decode > provisioning_profiles/siri_intents.mobileprovision
        echo setup keychain
        
        fastlane app_store build_number:${{ github.run_number }} skip_download_profiles:true
